name = "5etools-character-sync"
main = "character-sync.js"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "5etools-characters"
database_id = "f2ed23f5-e012-45e2-98b0-7d00fdd6be00"

# Durable Object bindings
[[durable_objects.bindings]]
name = "ROOM_MANAGER"
class_name = "RoomManager"

# Durable Object migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomManager"]

[env.production]
name = "5etools-character-sync"

# D1 Database binding for production
[[env.production.d1_databases]]
binding = "DB"
database_name = "5etools-characters"
database_id = "f2ed23f5-e012-45e2-98b0-7d00fdd6be00"

# Durable Object bindings for production
[[env.production.durable_objects.bindings]]
name = "ROOM_MANAGER"
class_name = "RoomManager"

[env.development] 
name = "5etools-character-sync-dev"

# D1 Database binding for development
[[env.development.d1_databases]]
binding = "DB"
database_name = "5etools-characters"
database_id = "f2ed23f5-e012-45e2-98b0-7d00fdd6be00"

# Durable Object bindings for development
[[env.development.durable_objects.bindings]]
name = "ROOM_MANAGER"
class_name = "RoomManager"
